query getFeaturedProducts($first: Int = 5) {
  products(
    first: $first
    where: { 
      typeNotIn: EXTERNAL, 
      visibility: VISIBLE, 
      featured: true,
      minPrice: 0, 
      status: "publish" 
    }
  ) {
    nodes {
      name
      slug
      type
      databaseId
      id
      averageRating
      reviewCount
      ...Terms
      ...ProductCategories
      ...SimpleProduct
      ...VariableProduct
    }
  }
}