query searchProducts($search: String, $first: Int = 9999) {
  products(
    first: $first
    where: {
      search: $search,
      typeNotIn: EXTERNAL,
      visibility: VISIBLE,
      status: "publish",
      # Include SKU search
      sku: $search
    }
  ) {
    nodes {
      name
      slug
      type
      databaseId
      id
      sku
      averageRating
      reviewCount
      ...Terms
      ...ProductCategories
      ...SimpleProduct
      ...VariableProduct
    }
  }
}